events {
    worker_connections 1024;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream; # Исправил опечатку (было octec)

    sendfile        on;
    keepalive_timeout  65;

    # Определяем бэкенд один раз здесь
    upstream python_app {
        server app:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # Исправляем путь к HTML: добавляем /html в конец root
        location ~ ^/(index|images)\.html$ {
            root /usr/share/nginx/html/static/html;
            try_files $uri =404;
        }

        location /static/ {
            alias /usr/share/nginx/html/static/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        location /images/ {
            alias /usr/share/nginx/html/images/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        location = / {
            return 301 /index.html;
        }

        # Проксируем на бэкенд БЕЗ указания порта (он взят из upstream)
        location / {
            proxy_pass http://python_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}